DROP DATABASE IF EXISTS Problem_3;
CREATE DATABASE Problem_3;
USE Problem_3;
CREATE TABLE people (
	id INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
	name VARCHAR(50) NOT NULL
);

CREATE TABLE place (
	id INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
	name VARCHAR(50) NOT NULL,
	lat DECIMAL(20,15) NOT NULL,
	lng DECIMAL(20,15) NOT NULL
);

CREATE TABLE date_date (
	id INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
	date DATE NOT NULL
);

CREATE TABLE music (
	id INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
	piece VARCHAR(255) NOT NULL
);

CREATE TABLE review (
	id INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
	music INTEGER NOT NULL,
	author INTEGER NOT NULL,
	summary VARCHAR (255) NOT NULL,
	FOREIGN KEY (music) REFERENCES music(id),
	FOREIGN KEY (author) REFERENCES people(id)
);

CREATE TABLE date_place (
	id INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
	place INTEGER NOT NULL,
	date_place INTEGER NOT NULL,
	music INTEGER NOT NULL,
	FOREIGN KEY (place) REFERENCES place(id),
	FOREIGN KEY (date_place) REFERENCES date_date(id),
	FOREIGN KEY (music) REFERENCES music(id)
);

CREATE TABLE date_performer (
	id INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
	date_performer INTEGER NOT NULL,
	performer INTEGER NOT NULL,
	music INTEGER NOT NULL,
	FOREIGN KEY (date_performer) REFERENCES date_date(id),
	FOREIGN KEY (performer) REFERENCES people(id),
	FOREIGN KEY (music) REFERENCES music(id)
);

CREATE TABLE date_review (
	id INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
	date_review INTEGER NOT NULL,
	review INTEGER NOT NULL,
	FOREIGN KEY (date_review) REFERENCES date_date(id),
	FOREIGN KEY (review) REFERENCES review(id)
);