DROP DATABASE IF EXISTS Problem_1;
CREATE DATABASE Problem_1;
USE Problem_1;
CREATE TABLE books (
	id INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
	title VARCHAR(255) NOT NULL,
	author VARCHAR(50) NOT NULL,
	pubilshed DATE NOT NULL
);

CREATE TABLE people (
	id INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
	name VARCHAR(50) NOT NULL,
	borrowed_books_id INTEGER,
	FOREIGN KEY (borrowed_books_id) REFERENCES books(id)
);

CREATE TABLE return_date (
	id INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
	return_date DATE NOT NULL,
	borrowed_books_id INTEGER NOT NULL,
	borrower_id INTEGER NOT NULL,
	FOREIGN KEY (borrowed_books_id) REFERENCES books(id),
	FOREIGN KEY (borrower_id) REFERENCES people(id)
);

