DROP DATABASE IF EXISTS Problem_3;
CREATE DATABASE Problem_3;
USE Problem_3;
CREATE TABLE people (
	id INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
	name VARCHAR(50) NOT NULL
);

CREATE TABLE place (
	id INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
	name VARCHAR(50) NOT NULL,
	lat DECIMAL(20,15) NOT NULL,
	lng DECIMAL(20,15) NOT NULL
);

CREATE TABLE date (
	id INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
	place INTEGER NOT NULL,
	performer INTEGER,
	reviewer INTEGER,
	date DATE NOT NULL,
	FOREIGN KEY (place) REFERENCES place(id),
	FOREIGN KEY (performer) REFERENCES people(id),
	FOREIGN KEY (reviewer) REFERENCES people(id)
);

CREATE TABLE music (
	id INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
	piece VARCHAR(255) NOT NULL,
	place INTEGER NOT NULL,
	date_of_performance INTEGER NOT NULL,
	performer INTEGER NOT NULL,
	reviewer INTEGER,
	FOREIGN KEY (place) REFERENCES place(id),
	FOREIGN KEY (date_of_performance) REFERENCES date(id),
	FOREIGN KEY (performer) REFERENCES people(id),
	FOREIGN KEY (reviewer) REFERENCES people(id)
);

CREATE TABLE review (
	id INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
	music INTEGER NOT NULL,
	author INTEGER NOT NULL,
	summary VARCHAR (255) NOT NULL,
	FOREIGN KEY (music) REFERENCES music(id),
	FOREIGN KEY (author) REFERENCES people(id)
);

